// ECHIDNA Cap'n Proto C-ABI Bridge
//
// C-compatible functions for IPC between the Rust core and the Julia ML
// layer over Unix domain sockets. Actual Cap'n Proto serialisation will
// be generated by `just capnp-gen` in L1 wave 1; until then the
// gnn_rank function is a clearly-labelled stub that returns an error
// code so callers can wire the ABI boundary and test error paths now.
//
// Error reporting follows the same pattern as main.zig:
//   - Return value: 0 = success, negative = error
//   - Detail: call echidna_capnp_status_message(code, buf, buflen)
//   - Thread-local storage makes this safe for concurrent Rust threads.
//
// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>

const std = @import("std");
const builtin = @import("builtin");

const BRIDGE_VERSION = "0.1.0";

// ─── Status codes ─────────────────────────────────────────────────────────────

pub const CapnpStatus = enum(c_int) {
    ok                   =  0,
    not_connected        = -1,
    stub_not_implemented = -2,
    invalid_param        = -3,
    io_error             = -4,
    connect_failed       = -6,
    unknown_error        = -99,
};

// ─── Thread-local error storage ───────────────────────────────────────────────

threadlocal var last_error_buf: [512]u8 = undefined;
threadlocal var last_error_len: usize = 0;
threadlocal var last_error_status: CapnpStatus = .ok;

fn setError(status: CapnpStatus, comptime fmt: []const u8, args: anytype) void {
    last_error_status = status;
    const result = std.fmt.bufPrint(&last_error_buf, fmt, args) catch blk: {
        const msg = "(error message truncated)";
        @memcpy(last_error_buf[0..msg.len], msg);
        break :blk last_error_buf[0..msg.len];
    };
    last_error_len = result.len;
}

fn clearError() void {
    last_error_status = .ok;
    last_error_len = 0;
}

// ─── C-compatible structs ─────────────────────────────────────────────────────

/// GNN rank request passed across the C-ABI boundary.
/// The graph is encoded as a pre-serialised JSON blob for the stub phase;
/// L1 wave 1 replaces this with a zero-copy Cap'n Proto builder once
/// `capnp compile -ozig` output is available.
pub const EchidnaGnnRequest = extern struct {
    /// Opaque request identifier (null-terminated, max 63 chars + NUL).
    request_id: [64]u8,
    /// Pointer to UTF-8 JSON array of graph nodes (NOT null-terminated).
    graph_nodes_json_ptr: [*c]const u8,
    /// Byte length of graph_nodes_json_ptr.
    graph_nodes_len: usize,
    /// Maximum number of premises to return (must be > 0; default 20).
    top_k: u32,
    /// Minimum score threshold; results below this are suppressed.
    min_score: f32,
};

/// GNN rank response returned across the C-ABI boundary.
/// On success the caller owns rankings_json_ptr and MUST call
/// echidna_capnp_free_response to release it.
pub const EchidnaGnnResponse = extern struct {
    /// Echo of the request_id from the matching EchidnaGnnRequest.
    request_id: [64]u8,
    /// Pointer to UTF-8 JSON array of PremiseScore objects. NULL on error.
    rankings_json_ptr: [*c]const u8,
    /// Byte length of rankings_json (0 on error).
    rankings_len: u32,
    /// Round-trip wall-clock time in milliseconds.
    elapsed_ms: u64,
};

// ─── Exported C-ABI functions ─────────────────────────────────────────────────

/// Open a Unix domain socket connection to the ECHIDNA IPC endpoint.
///
/// Returns: ≥ 0 file descriptor on success, -1 on failure.
/// On failure call echidna_capnp_status_message(-1, buf, buflen) for details.
export fn echidna_capnp_connect(sock_path: [*c]const u8) callconv(.C) i32 {
    if (sock_path == null) {
        setError(.invalid_param, "sock_path must not be NULL", .{});
        return -1;
    }
    const path_slice = std.mem.sliceTo(sock_path, 0);
    if (path_slice.len == 0) {
        setError(.invalid_param, "sock_path must not be empty", .{});
        return -1;
    }

    const addr = std.net.Address.initUnix(path_slice) catch |err| {
        setError(.connect_failed, "invalid socket path '{s}': {}", .{ path_slice, err });
        return -1;
    };

    const sock = std.net.tcpConnectToAddress(addr) catch |err| {
        setError(.connect_failed, "connect to '{s}' failed: {}", .{ path_slice, err });
        return -1;
    };

    clearError();
    return sock.handle;
}

/// Close a file descriptor previously returned by echidna_capnp_connect.
/// Safe to call with fd < 0 (no-op).
export fn echidna_capnp_close(fd: i32) callconv(.C) void {
    if (fd < 0) return;
    std.posix.close(@intCast(fd));
}

/// Send a GNN rank request and receive the response.
///
/// STUB — returns CapnpStatus.stub_not_implemented until L1 wave 1 lands.
/// The response struct is zeroed before returning so callers that check
/// rankings_json_ptr for NULL get a well-defined value.
///
/// Returns: 0 on success, negative on error.
///   -2 (stub_not_implemented): expected until `just capnp-gen` is run in L1 wave 1.
export fn echidna_capnp_gnn_rank(
    fd: i32,
    req: *const EchidnaGnnRequest,
    resp: *EchidnaGnnResponse,
) callconv(.C) i32 {
    if (fd < 0) {
        setError(.not_connected, "fd {d} is invalid (not connected)", .{fd});
        return @intFromEnum(CapnpStatus.not_connected);
    }
    _ = req;
    resp.* = std.mem.zeroes(EchidnaGnnResponse);
    setError(
        .stub_not_implemented,
        "L1 wave 1: Cap'n Proto bindings not yet generated — run `just capnp-gen`",
        .{},
    );
    return @intFromEnum(CapnpStatus.stub_not_implemented);
}

/// Free a response buffer allocated by echidna_capnp_gnn_rank.
/// No-op in the stub (no allocations are made). Must be called in the real
/// implementation to release the Cap'n Proto message buffer.
export fn echidna_capnp_free_response(resp: *EchidnaGnnResponse) callconv(.C) void {
    _ = resp;
}

/// Write a human-readable description of `status` into `buf`.
///
/// If the most recent call on this thread stored a detailed message for
/// this status code, that message is used. Otherwise a generic description
/// is written. Output is always null-terminated and never exceeds buflen bytes.
export fn echidna_capnp_status_message(
    status: i32,
    buf: [*c]u8,
    buflen: usize,
) callconv(.C) void {
    if (buflen == 0 or buf == null) return;

    if (last_error_len > 0 and @intFromEnum(last_error_status) == status) {
        const src = last_error_buf[0..last_error_len];
        const n = @min(src.len, buflen - 1);
        @memcpy(buf[0..n], src[0..n]);
        buf[n] = 0;
        return;
    }

    const generic: []const u8 = switch (status) {
        0   => "ok",
        -1  => "not connected",
        -2  => "stub not implemented (L1 wave 1 pending)",
        -3  => "invalid parameter",
        -4  => "I/O error",
        -6  => "connect failed",
        -99 => "unknown error",
        else => "unrecognised status code",
    };
    const n = @min(generic.len, buflen - 1);
    @memcpy(buf[0..n], generic[0..n]);
    buf[n] = 0;
}
