# SPDX-License-Identifier: PMPL-1.0-or-later

defmodule EchidnaDocs.Application do
  @moduledoc """
  ECHIDNA Documentation Server.

  Serves static documentation generated by ddraig-ssg,
  with http-capability-gateway policy enforcement and
  consent-aware-http AIBDP declarations.
  """

  use Application

  @impl true
  def start(_type, _args) do
    port = System.get_env("PORT", "4040") |> String.to_integer()

    children = [
      {Plug.Cowboy, scheme: :http, plug: EchidnaDocs.Router, options: [port: port]}
    ]

    opts = [strategy: :one_for_one, name: EchidnaDocs.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
