// SPDX-License-Identifier: PMPL-1.0-or-later
// GNN training pipeline integration test

#[cfg(test)]
mod gnn_training_integration_tests {
    use echidna::diagnostics::{HealthStatus, load_training_metrics, update_health_with_metrics};
    use std::path::Path;

    /// Test: Load metrics from actual training file and update health
    #[test]
    fn test_load_and_apply_training_metrics() {
        // Load metrics from the file generated by Julia training
        let metrics_path = Path::new("models/training_metrics.json");
        
        if !metrics_path.exists() {
            println!("⚠ Training metrics file not found at {:?}", metrics_path);
            println!("Run: julia src/julia/train_and_evaluate.jl");
            return;
        }
        
        let metrics = load_training_metrics(metrics_path)
            .expect("Failed to load training metrics");
        
        // Verify metrics were parsed correctly
        assert_eq!(metrics.status, "completed");
        assert!(metrics.nDCG > 0.0, "nDCG should be > 0");
        assert!(metrics.MRR > 0.0, "MRR should be > 0");
        assert_eq!(metrics.epochs_trained, 50);
        assert!(metrics.training_data_size > 0);
        
        // Create health status and apply metrics
        let mut health = HealthStatus::new();
        
        // Before update, GNN is not loaded
        assert!(!health.gnn_model_health.is_loaded);
        assert_eq!(health.gnn_model_health.last_validation_nDCG, 0.0);
        
        // Apply metrics
        update_health_with_metrics(&mut health, &metrics);
        
        // After update, GNN should be loaded with real metrics
        assert!(health.gnn_model_health.is_loaded);
        assert_eq!(health.gnn_model_health.last_validation_nDCG, metrics.nDCG);
        assert_eq!(health.gnn_model_health.last_validation_MRR, metrics.MRR);
        assert!(health.gnn_model_health.nDCG_meets_threshold);
        assert!(health.gnn_model_health.last_trained.is_some());
        
        // Verify health percentage is now higher (GNN contributes 20%)
        let health_pct = health.health_percentage();
        assert!(health_pct >= 20.0, "With GNN loaded at {:.2}, health should be >= 20%", metrics.nDCG);
        
        println!("✓ Training metrics loaded successfully");
        println!("  nDCG:  {}", metrics.nDCG);
        println!("  MRR:   {}", metrics.MRR);
        println!("  Health: {:.1}%", health_pct);
    }
}
