// SPDX-FileCopyrightText: 2026 ECHIDNA Project Team
// SPDX-License-Identifier: PMPL-1.0-or-later

//! Alt-Ergo backend
//!
//! Alt-Ergo is an SMT solver with native support for polymorphic first-order logic.
//! Designed for program verification (Why3, Frama-C integration).
//!
//! Features:
//! - Polymorphic first-order logic
//! - Built-in theories (arithmetic, arrays, records, ADTs)
//! - Native Alt-Ergo format or SMT-LIB2
//! - Excellent integration with Why3

#![allow(dead_code)]

use anyhow::{Context, Result};
use async_trait::async_trait;
use std::path::PathBuf;
use tokio::process::Command;

use super::{ProverBackend, ProverConfig, ProverKind};
use crate::core::{Goal, ProofState, Tactic, TacticResult, Term};

/// Alt-Ergo theorem prover backend
pub struct AltErgoBackend {
    config: ProverConfig,
}

impl AltErgoBackend {
    pub fn new(config: ProverConfig) -> Self {
        AltErgoBackend { config }
    }

    /// Convert proof state to Alt-Ergo native format
    fn to_altergo(&self, state: &ProofState) -> Result<String> {
        let mut ae = String::new();

        ae.push_str("(* Generated by ECHIDNA *)\n\n");

        // Axioms
        for (i, axiom) in state.context.axioms.iter().enumerate() {
            ae.push_str(&format!("axiom axiom_{} : {};\n", i, axiom));
        }

        ae.push('\n');

        // Goal
        if let Some(goal) = state.goals.first() {
            ae.push_str(&format!("goal conjecture : {};\n", goal.target));
        }

        Ok(ae)
    }

    /// Convert to SMT-LIB2 format (alternative)
    fn to_smtlib2(&self, state: &ProofState) -> Result<String> {
        let mut smt = String::new();

        smt.push_str("(set-logic ALL)\n");

        // Axioms
        for axiom in &state.context.axioms {
            smt.push_str(&format!("(assert {})\n", axiom));
        }

        // Goal (negated for refutation)
        if let Some(goal) = state.goals.first() {
            smt.push_str(&format!("(assert (not {}))\n", goal.target));
        }

        smt.push_str("(check-sat)\n");

        Ok(smt)
    }

    /// Parse Alt-Ergo output
    fn parse_result(&self, output: &str) -> Result<bool> {
        if output.contains("Valid") || output.contains("unsat") {
            Ok(true)
        } else if output.contains("Invalid") || output.contains("sat") {
            Ok(false)
        } else {
            Err(anyhow::anyhow!(
                "Alt-Ergo inconclusive: {}",
                output.lines().take(10).collect::<Vec<_>>().join("\n")
            ))
        }
    }
}

#[async_trait]
impl ProverBackend for AltErgoBackend {
    fn kind(&self) -> ProverKind {
        ProverKind::AltErgo
    }

    async fn version(&self) -> Result<String> {
        let output = Command::new(&self.config.executable)
            .arg("--version")
            .output()
            .await
            .context("Failed to run alt-ergo --version")?;

        let stdout = String::from_utf8_lossy(&output.stdout);
        Ok(stdout
            .lines()
            .next()
            .unwrap_or("unknown")
            .trim()
            .to_string())
    }

    async fn parse_file(&self, path: PathBuf) -> Result<ProofState> {
        let content = tokio::fs::read_to_string(&path)
            .await
            .context("Failed to read proof file")?;
        let mut state = self.parse_string(&content).await?;
        state.metadata.insert(
            "source_path".to_string(),
            serde_json::Value::String(path.to_string_lossy().into_owned()),
        );
        Ok(state)
    }

    async fn parse_string(&self, content: &str) -> Result<ProofState> {
        let mut state = ProofState::default();
        state.metadata.insert(
            "altergo_source".to_string(),
            serde_json::Value::String(content.to_string()),
        );

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with("(*") {
                continue;
            }

            if line.starts_with("axiom ") {
                if let Some(formula) = line.split(':').nth(1) {
                    let formula = formula.trim_end_matches(';').trim();
                    state.context.axioms.push(formula.to_string());
                }
            } else if line.starts_with("goal ") {
                if let Some(formula) = line.split(':').nth(1) {
                    let formula = formula.trim_end_matches(';').trim();
                    state.goals.push(Goal {
                        id: format!("goal_{}", state.goals.len()),
                        target: Term::Const(formula.to_string()),
                        hypotheses: vec![],
                    });
                }
            }
        }

        Ok(state)
    }

    async fn apply_tactic(&self, _state: &ProofState, _tactic: &Tactic) -> Result<TacticResult> {
        Err(anyhow::anyhow!(
            "Alt-Ergo is fully automated - interactive tactics not supported"
        ))
    }

    async fn verify_proof(&self, state: &ProofState) -> Result<bool> {
        // Prefer the original .ae source — `to_altergo(state)` round-trips
        // Alt-Ergo syntax through the generic Term IR, which mangles
        // anything beyond toy inputs.
        let (path_to_check, is_temp): (PathBuf, bool) =
            if let Some(p) = state.metadata.get("source_path").and_then(|v| v.as_str()) {
                (PathBuf::from(p), false)
            } else if let Some(src) = state
                .metadata
                .get("altergo_source")
                .and_then(|v| v.as_str())
            {
                let tmp = std::env::temp_dir()
                    .join(format!("echidna_altergo_{}.ae", uuid::Uuid::new_v4()));
                tokio::fs::write(&tmp, src)
                    .await
                    .context("Failed to write temp file")?;
                (tmp, true)
            } else {
                let ae_code = self.to_altergo(state)?;
                let tmp = std::env::temp_dir().join("echidna_altergo_input.ae");
                tokio::fs::write(&tmp, ae_code.as_bytes())
                    .await
                    .context("Failed to write temp file")?;
                (tmp, true)
            };

        let output = tokio::time::timeout(
            tokio::time::Duration::from_secs(self.config.timeout + 5),
            Command::new(&self.config.executable)
                .arg(&path_to_check)
                .arg("--timelimit")
                .arg(format!("{}", self.config.timeout))
                .output(),
        )
        .await
        .context("Alt-Ergo timed out")??;

        if is_temp {
            let _ = tokio::fs::remove_file(&path_to_check).await;
        }

        let stdout = String::from_utf8_lossy(&output.stdout);
        self.parse_result(&stdout)
    }

    async fn export(&self, state: &ProofState) -> Result<String> {
        self.to_altergo(state)
    }

    async fn suggest_tactics(&self, _state: &ProofState, _limit: usize) -> Result<Vec<Tactic>> {
        Ok(vec![])
    }

    async fn search_theorems(&self, _pattern: &str) -> Result<Vec<String>> {
        Ok(vec![])
    }

    fn config(&self) -> &ProverConfig {
        &self.config
    }

    fn set_config(&mut self, config: ProverConfig) {
        self.config = config;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_altergo_kind() {
        let config = ProverConfig {
            executable: PathBuf::from("alt-ergo"),
            timeout: 30,
            ..Default::default()
        };
        let backend = AltErgoBackend::new(config);
        assert_eq!(backend.kind(), ProverKind::AltErgo);
    }

    #[test]
    fn test_altergo_to_altergo_format() {
        let config = ProverConfig {
            executable: PathBuf::from("alt-ergo"),
            timeout: 30,
            ..Default::default()
        };
        let backend = AltErgoBackend::new(config);

        let mut state = ProofState::default();
        state
            .context
            .axioms
            .push("forall x: int. x >= 0".to_string());
        state.goals.push(Goal {
            id: "goal_0".to_string(),
            target: Term::Const("true".to_string()),
            hypotheses: vec![],
        });

        let ae = backend.to_altergo(&state).unwrap();
        assert!(ae.contains("Generated by ECHIDNA"));
        assert!(ae.contains("axiom axiom_0"));
        assert!(ae.contains("goal conjecture"));
    }

    #[test]
    fn test_altergo_to_smtlib2() {
        let config = ProverConfig {
            executable: PathBuf::from("alt-ergo"),
            timeout: 30,
            ..Default::default()
        };
        let backend = AltErgoBackend::new(config);

        let mut state = ProofState::default();
        state.context.axioms.push("(> x 0)".to_string());
        state.goals.push(Goal {
            id: "goal_0".to_string(),
            target: Term::Const("(>= x 0)".to_string()),
            hypotheses: vec![],
        });

        let smt = backend.to_smtlib2(&state).unwrap();
        assert!(smt.contains("(set-logic ALL)"));
        assert!(smt.contains("(assert (> x 0))"));
        assert!(smt.contains("(assert (not (>= x 0)))"));
        assert!(smt.contains("(check-sat)"));
    }

    #[test]
    fn test_altergo_parse_result_valid() {
        let config = ProverConfig::default();
        let backend = AltErgoBackend::new(config);

        assert!(backend.parse_result("Valid\n").unwrap());
        assert!(backend.parse_result("unsat\n").unwrap());
    }

    #[test]
    fn test_altergo_parse_result_invalid() {
        let config = ProverConfig::default();
        let backend = AltErgoBackend::new(config);

        assert!(!backend.parse_result("Invalid\n").unwrap());
        assert!(!backend.parse_result("sat\n").unwrap());
    }

    #[test]
    fn test_altergo_parse_result_inconclusive() {
        let config = ProverConfig::default();
        let backend = AltErgoBackend::new(config);

        assert!(backend.parse_result("I don't know\n").is_err());
    }

    #[tokio::test]
    async fn test_altergo_parse_string() {
        let config = ProverConfig::default();
        let backend = AltErgoBackend::new(config);

        let content = "axiom a1 : forall x: int. x >= 0;\ngoal conjecture : true;\n";
        let state = backend.parse_string(content).await.unwrap();

        assert_eq!(state.context.axioms.len(), 1);
        assert_eq!(state.goals.len(), 1);
    }

    #[tokio::test]
    async fn test_altergo_parse_string_empty() {
        let config = ProverConfig::default();
        let backend = AltErgoBackend::new(config);

        let state = backend.parse_string("").await.unwrap();
        assert!(state.goals.is_empty());
        assert!(state.context.axioms.is_empty());
    }
}
