// SPDX-FileCopyrightText: 2026 ECHIDNA Project Team
// SPDX-License-Identifier: PMPL-1.0-or-later

//! SPASS backend
//!
//! SPASS (System for Proving Associative Sets with Selections) is a
//! first-order theorem prover with a focus on sorted logic.
//!
//! Features:
//! - First-order logic with equality and sorts
//! - Native SPASS format (DFG format)
//! - Superposition calculus
//! - Sort handling for typed first-order logic

#![allow(dead_code)]

use anyhow::{Context, Result};
use async_trait::async_trait;
use std::path::PathBuf;
use std::process::Stdio;
use tokio::process::Command;

use super::{ProverBackend, ProverConfig, ProverKind};
use crate::core::{Goal, ProofState, Tactic, TacticResult, Term};

/// SPASS theorem prover backend
pub struct SPASSBackend {
    config: ProverConfig,
}

impl SPASSBackend {
    pub fn new(config: ProverConfig) -> Self {
        SPASSBackend { config }
    }

    /// Convert proof state to SPASS DFG format
    fn to_dfg(&self, state: &ProofState) -> Result<String> {
        let mut dfg = String::new();

        dfg.push_str("begin_problem(Generated).\n\n");
        dfg.push_str("list_of_descriptions.\n");
        dfg.push_str("name({*Generated by ECHIDNA*}).\n");
        dfg.push_str("author({*ECHIDNA*}).\n");
        dfg.push_str("status(unknown).\n");
        dfg.push_str("description({*Auto-generated problem*}).\n");
        dfg.push_str("end_of_list.\n\n");

        // Axioms
        dfg.push_str("list_of_formulae(axioms).\n");
        for (i, axiom) in state.context.axioms.iter().enumerate() {
            dfg.push_str(&format!("formula({}, {}).\n", axiom, i));
        }
        dfg.push_str("end_of_list.\n\n");

        // Conjecture
        if let Some(goal) = state.goals.first() {
            dfg.push_str("list_of_formulae(conjectures).\n");
            dfg.push_str(&format!("formula({}).\n", goal.target));
            dfg.push_str("end_of_list.\n\n");
        }

        dfg.push_str("end_problem.\n");

        Ok(dfg)
    }

    /// Parse SPASS output
    fn parse_result(&self, output: &str) -> Result<bool> {
        if output.contains("Proof found")
            || output.contains("proof found")
            || output.contains("SPASS beiseite: Proof")
        {
            Ok(true)
        } else if output.contains("Completion found") {
            Ok(false)
        } else {
            Err(anyhow::anyhow!(
                "SPASS inconclusive: {}",
                output.lines().take(10).collect::<Vec<_>>().join("\n")
            ))
        }
    }
}

#[async_trait]
impl ProverBackend for SPASSBackend {
    fn kind(&self) -> ProverKind {
        ProverKind::SPASS
    }

    async fn version(&self) -> Result<String> {
        let output = Command::new(&self.config.executable)
            .output()
            .await
            .context("Failed to run SPASS")?;

        let stdout = String::from_utf8_lossy(&output.stdout);
        for line in stdout.lines() {
            if line.contains("SPASS") && line.contains("Version") {
                return Ok(line.trim().to_string());
            }
        }
        Ok("unknown".to_string())
    }

    async fn parse_file(&self, path: PathBuf) -> Result<ProofState> {
        let content = super::bounded_read_proof_file(&path)
            .await
            .context("Failed to read proof file")?;
        let mut state = self.parse_string(&content).await?;
        state.metadata.insert(
            "source_path".to_string(),
            serde_json::Value::String(path.to_string_lossy().into_owned()),
        );
        Ok(state)
    }

    async fn parse_string(&self, content: &str) -> Result<ProofState> {
        let mut state = ProofState::default();
        state.metadata.insert(
            "spass_source".to_string(),
            serde_json::Value::String(content.to_string()),
        );

        let mut in_axioms = false;
        let mut in_conjectures = false;

        for line in content.lines() {
            let line = line.trim();

            if line.starts_with("list_of_formulae(axioms)") {
                in_axioms = true;
                in_conjectures = false;
            } else if line.starts_with("list_of_formulae(conjectures)") {
                in_conjectures = true;
                in_axioms = false;
            } else if line.starts_with("end_of_list") {
                in_axioms = false;
                in_conjectures = false;
            } else if line.starts_with("formula(") {
                if let Some(formula) = line
                    .strip_prefix("formula(")
                    .and_then(|s| s.strip_suffix(")."))
                {
                    if in_axioms {
                        state.context.axioms.push(formula.to_string());
                    } else if in_conjectures {
                        state.goals.push(Goal {
                            id: format!("goal_{}", state.goals.len()),
                            target: Term::Const(formula.to_string()),
                            hypotheses: vec![],
                        });
                    }
                }
            }
        }

        Ok(state)
    }

    async fn apply_tactic(&self, _state: &ProofState, _tactic: &Tactic) -> Result<TacticResult> {
        Err(anyhow::anyhow!(
            "SPASS is fully automated - interactive tactics not supported"
        ))
    }

    async fn verify_proof(&self, state: &ProofState) -> Result<bool> {
        // Prefer the original DFG source when parse_file / parse_string
        // stashed it.  `to_dfg(state)` reconstructs DFG from the parsed
        // conjecture list, which silently mangles anything beyond toy
        // single-atom formulae.  If a real path is available, pass that
        // directly; otherwise materialise the stashed source (or the
        // lossy reconstruction) to a temp file.
        //
        // SPASS rejects input on stdin — the upstream binary parses the
        // stdin stream as additional command-line flags — so we always
        // pass a file path as the final positional argument.
        let path_to_check: PathBuf =
            if let Some(p) = state.metadata.get("source_path").and_then(|v| v.as_str()) {
                PathBuf::from(p)
            } else {
                let dfg_code = state
                    .metadata
                    .get("spass_source")
                    .and_then(|v| v.as_str())
                    .map(ToOwned::to_owned)
                    .map(Ok)
                    .unwrap_or_else(|| self.to_dfg(state))?;
                let tmp = std::env::temp_dir()
                    .join(format!("echidna_spass_{}.dfg", uuid::Uuid::new_v4()));
                tokio::fs::write(&tmp, dfg_code).await?;
                tmp
            };

        // Don't pass -PGiven=0 / -PProblem=0 here: those suppress the
        // "SPASS beiseite: Proof found." banner that `parse_result`
        // matches on.
        // SPASS flag syntax is `-Name=Value` (not `-Name Value`).  Passing
        // them separated makes SPASS parse the number as a filename and
        // exit with "Error in opening file N for reading".
        let output = tokio::time::timeout(
            tokio::time::Duration::from_secs(self.config.timeout + 5),
            Command::new(&self.config.executable)
                .arg(format!("-TimeLimit={}", self.config.timeout))
                .arg(&path_to_check)
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .output(),
        )
        .await
        .context("SPASS timed out")??;

        let stdout = String::from_utf8_lossy(&output.stdout);
        self.parse_result(&stdout)
    }

    async fn export(&self, state: &ProofState) -> Result<String> {
        self.to_dfg(state)
    }

    async fn suggest_tactics(&self, _state: &ProofState, _limit: usize) -> Result<Vec<Tactic>> {
        Ok(vec![])
    }

    async fn search_theorems(&self, _pattern: &str) -> Result<Vec<String>> {
        Ok(vec![])
    }

    fn config(&self) -> &ProverConfig {
        &self.config
    }

    fn set_config(&mut self, config: ProverConfig) {
        self.config = config;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_spass_kind() {
        let config = ProverConfig {
            executable: PathBuf::from("SPASS"),
            timeout: 30,
            ..Default::default()
        };
        let backend = SPASSBackend::new(config);
        assert_eq!(backend.kind(), ProverKind::SPASS);
    }

    #[test]
    fn test_spass_dfg_export() {
        let config = ProverConfig::default();
        let backend = SPASSBackend::new(config);

        let mut state = ProofState::default();
        state.context.axioms.push("p(a)".to_string());
        state.goals.push(Goal {
            id: "goal_0".to_string(),
            target: Term::Const("p(a)".to_string()),
            hypotheses: vec![],
        });

        let dfg = backend.to_dfg(&state).unwrap();
        assert!(dfg.contains("begin_problem(Generated)"));
        assert!(dfg.contains("list_of_formulae(axioms)"));
        assert!(dfg.contains("list_of_formulae(conjectures)"));
        assert!(dfg.contains("end_problem"));
    }

    #[test]
    fn test_spass_parse_result_proof_found() {
        let config = ProverConfig::default();
        let backend = SPASSBackend::new(config);

        assert!(backend
            .parse_result("SPASS beiseite: Proof found.\n")
            .unwrap());
        assert!(backend
            .parse_result("Proof found for clause set.\n")
            .unwrap());
    }

    #[test]
    fn test_spass_parse_result_completion() {
        let config = ProverConfig::default();
        let backend = SPASSBackend::new(config);

        assert!(!backend.parse_result("Completion found.\n").unwrap());
    }

    #[test]
    fn test_spass_parse_result_inconclusive() {
        let config = ProverConfig::default();
        let backend = SPASSBackend::new(config);

        assert!(backend.parse_result("ran out of time\n").is_err());
    }

    #[tokio::test]
    async fn test_spass_parse_string() {
        let config = ProverConfig::default();
        let backend = SPASSBackend::new(config);

        let dfg = "begin_problem(Test).\n\
                    list_of_formulae(axioms).\n\
                    formula(p(a)).\n\
                    end_of_list.\n\
                    list_of_formulae(conjectures).\n\
                    formula(p(a)).\n\
                    end_of_list.\n\
                    end_problem.\n";

        let state = backend.parse_string(dfg).await.unwrap();
        assert_eq!(state.context.axioms.len(), 1);
        assert_eq!(state.goals.len(), 1);
    }

    #[tokio::test]
    async fn test_spass_export_roundtrip() {
        let config = ProverConfig::default();
        let backend = SPASSBackend::new(config);

        let mut state = ProofState::default();
        state.context.axioms.push("implies(p, q)".to_string());
        state.goals.push(Goal {
            id: "goal_0".to_string(),
            target: Term::Const("q".to_string()),
            hypotheses: vec![],
        });

        let dfg = backend.export(&state).await.unwrap();
        assert!(dfg.contains("implies(p, q)"));
        assert!(dfg.contains("q"));
    }
}
